# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 14:34
from __future__ import unicode_literals

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170520_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(default=collection.models.Album.description_default),
        ),
    ]
